# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e6e51311b9946fb94385305fadf03aae9a3118e6e01f07a2ee9bb9bfb2f3c1b68ad8f803da3f45438bbcc97ee19b227cd315ea2795985ef9d80be6805651446

test:
  secret_key_base: 0a258d77eb1fdcda25d3137cdd22ede3dc1fb734f9b1bbdbc1c05296324b16add2b1923c0d1fc9a09e5913f4bb04eef6b7e519efef5a73ed3455e67f52951d2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
